services:
  backend:
    restart: always
    build:
      context: ./server
    container_name: backend
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=postgresql://postgres@host.docker.internal:5432/cadry

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 8080:80
    container_name: nginx
  # rabbitmq:
  #   image: rabbitmq:management-alpine
  #   container_name: rabbitmq
  #   ports:
  #     - 15672:15672
  #     - 5672:5672
