services:
  cadry-backend:
    build:
      context: ./server
      dockerfile: ./server/apps/cadry-server/Dockerfile
    container_name: cadry-backend
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=postgresql://postgres@host.docker.internal:5432/cadry

  import-service:
    build:
      context: ./server
      dockerfile: ./server/apps/import/Dockerfile
    container_name: import-service
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=postgresql://postgres@host.docker.internal:5432/cadry

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 8080:80

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
