services:
  backend:
    build:
      context: server
      dockerfile: apps/cadry-server/Dockerfile
    container_name: backend
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=postgresql://postgres@host.docker.internal:5432/cadry
      - RABBIT_MQ_URI=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    volumes:
      - ./server/files:/usr/app/src/files:rw

  import:
    build:
      context: server
      dockerfile: apps/import/Dockerfile
    container_name: import
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=postgresql://postgres@host.docker.internal:5432/cadry
      - RABBIT_MQ_URI=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    volumes:
      - ./server/files:/usr/app/src/files:rw

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - backend

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
