-- AlterTable
ALTER TABLE "organizations" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "phone_number" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "web" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL;
